packages:
  - 'packages/*'
  - 'docs'
  - '.claude/skills/pumped-design/examples/skill-examples'

catalog:
  "@hono/node-server": ^1.19.9
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/sdk-trace-base": ^1.30.1
  "@opentelemetry/exporter-trace-otlp-http": ^0.211.0
  "@opentelemetry/resources": ^1.30.1
  "@opentelemetry/semantic-conventions": ^1.39.0
  "@opentui/core": ^0.1.77
  "@opentui/react": ^0.1.77
  "@types/node": ^20.19.33
  "@types/react": ^19.0.0
  hono: ^4.11.9
  react: ^19.0.0
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.18
