packages:
  - 'packages/*'
  - 'docs'
  - '.claude/skills/pumped-design/examples/skill-examples'

catalog:
  "@hono/node-server": ^1.13.8
  "@opentui/core": ^0.1.59
  "@opentui/react": ^0.1.59
  "@types/node": ^20.19.22
  "@types/react": ^19.0.0
  hono: ^4.7.0
  react: ^19.0.0
  tsdown: ^0.17.2
  tsx: ^4.19.4
  typescript: ^5.9.3
  vitest: ^4.0.15
