packages:
  - 'packages/*'
  - 'docs'
  - '.claude/skills/pumped-design/examples/skill-examples'

catalog:
  "@hono/node-server": ^1.19.8
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/sdk-trace-base": ^1.30.1
  "@opentelemetry/exporter-trace-otlp-http": ^0.209.0
  "@opentelemetry/resources": ^1.30.1
  "@opentelemetry/semantic-conventions": ^1.38.0
  "@opentui/core": ^0.1.72
  "@opentui/react": ^0.1.72
  "@types/node": ^20.19.28
  "@types/react": ^19.0.0
  hono: ^4.11.3
  react: ^19.0.0
  tsdown: ^0.19.0
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.17
